---
all:
  hosts:
    clus-mdt-core1:
      ansible_host: 172.22.225.24
    clus-mdt-core2:
      ansible_host: 172.22.225.25
    clus-mdt-spine1:
      ansible_host: 172.22.225.20
    clus-mdt-leaf1:
      ansible_host: 172.22.225.21
    clus-mdt-leaf2:
      ansible_host: 172.22.225.22
    clus-mdt-leaf3:
      ansible_host: 172.22.225.23
  children:
    spine:
      hosts:
        clus-mdt-spine1:
    leafs:
      hosts:
        clus-mdt-leaf1:
        clus-mdt-leaf2:
        clus-mdt-leaf3:
    core:
      hosts:
        clus-mdt-core1:
        clus-mdt-core2:
    fabric:
      children:
        spines:
        leafs:
