---
- name: Spine BGP Failure
  hosts: spine
  gather_facts: false

  vars:
    bgp_peer: 100.64.0.11
    shut_peer: yes

  tasks:
    - name: Shutdown BGP Peer on Spine
      cisco.nxos.nxos_bgp_global:
        config:
          as_number: 65001
          neighbors:
            - neighbor_address: "{{ bgp_peer }}"
              shutdown: "{{ shut_peer }}"
        state: merged
